
persist_dir: db/
knowledge_base_dir: data/

chroma:
  persist_directory: db/chroma/
  anonymized_telemetry: false

splitter:
  chunk_size: 2048
  chunk_overlap: 50

llm: huggingface
model_type: online # online,local,download
prompt_style: normal # normal or llama2


embeddings:
  model: sentence-transformers/all-MiniLM-L6-v2
#  model: hkunlp/instructor-large
#  model_kwargs:
#    device: cuda

ctransformers:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-GGML
  model_file: Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin
  model_type: llama
  config:
    context_length: 1024


huggingface:
  model: tiiuae/falcon-7b-instruct
  model_kwargs:
    temperature: 0.1
    max_length: 2000
    max_new_tokens: 2000
    #trust_remote_code: true
  pipeline_kwargs:
    max_new_tokens: 4000

openai:
  model: gpt-3.5-turbo-16k
  temperature: 0.0
  max_tokens: 2000
